### ISSUE TITLE
AWFI images time-delivery in AWS

### ISSUE THREAD

**Issue by schultzBruno** [fredliporace/cbers-on-aws#3]
Fred, why the AWFI images are getting more than seven days to be avaliable to download in AWS?
The MUX and PAN images did not show the same delay.

Thanks.

**Comment by fredliporace** [comment]
Thanks for the catch, there seems to be an issue in the ingestion procedure that may skip some scenes. I'll work on that and post the updates.

**Comment by fredliporace** [comment]
A quick fix was deployed and ingestion is resumed. It will take some days to ingest all the scenes from 08-15-2019 up to today, but new scenes should be added in one or two days.
