### ISSUE TITLE
CBERS4 Thermal Imager (IRS) data

### ISSUE THREAD

**Issue by mhelleis** [fredliporace/cbers-on-aws#4]
Hello Frederico,

If I understand correctly the thermal data from the IRS instrument is not hosted on AWS. I've tried to find some documentation on API access to get the data directly from http://www.dgi.inpe.br/catalogo/ but I couldn't find any way.

Since you pull the data apparently from there on a daily basis, could you point me to a way on how to accomplish that? That would be much appreciated. 

Thank you and kind regards,
Max

**Comment by fredliporace** [comment]
Hi Max,

The procedure I'm using is described [here](https://aws.amazon.com/blogs/publicsector/the-china-brazil-earth-resources-satellite-mission), for some reason the architecture image is missing so I'm attaching it below:

![CBER](https://user-images.githubusercontent.com/28077347/150560761-fdfe8620-4e40-47b8-94ee-fe3c199b5e2c.png)

Unfortunately there is no API to select and download the images so everything is done by simulating a request using Selenium and then checking the e-mails known if the images are available for download and the download link, which is different for each request.

I may publish the Selenium python script as a GIST if that helps.

**Comment by mhelleis** [comment]
Hi Frederico,
I had to take a deeper look to see if this approach would be worth the effort, which it isn't for now. Mostly because the time between data acquisition and data availability in the web portal is more than 12 h, at least for the sample I've checked.

Anyway, thank you very much for your help!
